### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by HanbumKo** [Daniel-Liu-c0deb0t/Java-Machine-Learning#6]
Someone who knows license well, please add license.

**Comment by Filius-Patris** [comment]
What should be the goal of the license?
Should
- commercial distribution
- distribution without author notice
- modified distribution
be allowed?
Will the distributor have to
- state the changes
- show the source
- mark the author
- or even ask him for permission?

These questions help to decide which license should be used.

**Comment by HanbumKo** [comment]
I think we should listen to Daniel's opinion

**Comment by Daniel-Liu-c0deb0t** [comment]
I think we should go with a permissive license like the MIT license. Or we can just keep it unlicensed like right now and not worry about it.

**Comment by HanbumKo** [comment]
Ok. We don't need to add license now. We will add that when the need arises.
